editable_component_service:
  url:   /editable_component_service
  param: { module: sfEditableComponent, action: update }

editable_component_auth_test_service:
  url:   /editable_component_auth_test_service
  param: { module: sfEditableComponentTestUtility, action: auth }